import vessim as vs
from datetime import datetime
import pandas as pd

def main():
    # 1. Setup environment 
    # sim_start: Start date and time of the simulation (datetime.now() for real-time).
    # step_size: (1 for real-time, 300 for 5-minute steps, etc).
    environment = vs.Environment(sim_start="2022-06-15 00:00:00", step_size=300)

    # 2. Define actors (producers and consumers)
    # Consumer: Our Data Center.
    # StaticSignal with a negative value indicates consumption in Watts.
    datacenter_load = vs.Actor(
        name="main_server", 
        signal=vs.StaticSignal(value=-1500)
    )
    # Producer: Wind turbine
    # 
    df_wind = pd.read_csv("C:\\Users\\piopi\\Desktop\\Centrale\\Systèmes d'énergie embarqués\\Projet Data Centers\\vessim\\codes-martin\\wind_data.csv", index_col=0, parse_dates=True)
    wind_plant = vs.Actor(
        name="wind_turbine",
        signal=vs.Trace(actual=df_wind["power_W"])
    )

    # 3. Define storage (batteries)
    # Limit the charge and battery behavior with parameters.
    # SimpleBattery is a basic battery model that can charge and discharge based on the microgrid's needs.
    # ClcBattery is a more complex model for lithium-ion batteries, which includes parameters like charge/discharge efficiency.
    # capacity: Total capacity of the battery in Watt-hours (Wh).
    # initial_soc: State of Charge at the start of the simulation from 0 to 1 (0% to 100%).
    # min_soc: Discharge limit (the battery will never discharge below this percentage).
    battery = vs.SimpleBattery(
        capacity=5000, 
        initial_soc=0.5, 
        min_soc=0.2
    )

    # 4. Choose the policy (manages how the microgrid operates)
    # "grid-connected": If the battery can't cover the load, it will draw power from the grid (default).
    # "islanded": Disconnected from the grid. If there's not enough energy, the simulation fails (power outage).
    # "custom": You can implement your own policy by subclassing vs.Policy and defining the logic in the decide() method.
    policy = vs.DefaultPolicy(mode="grid-connected")

    # 5. Create the microgrid (by combining actors, storage, and policy)
    environment.add_microgrid(
        name="my_datacenter",
        actors=[datacenter_load, wind_plant],
        storage=battery,
        policy=policy
    )

    # 6. The controller (Monitoring and API)
    # MemoryLogger logs all the simulation data in memory for later analysis and visualization.
    logger = vs.MemoryLogger()
    environment.add_controller(logger)
    # Optional: Add an API controller to expose the simulation state via a web server (for real-time monitoring or external control).
    # environment.add_controller(vs.Api(export_prometheus=True))

    # 7. Execute the simulation
    print("Starting simulation...")
    # until: Total simulation time in seconds (24 hours = 24 * 3600 seconds).
    environment.run(until=24 * 3600)
    print("Simulation completed!")

    # 8. Visualize results
    # Vessim provides built-in plotting functions to visualize the results from the logger.
    # 4 graphs are generated by default: actor power, delta power, battery state of charge and grid power.
    fig = vs.plot_result_df(logger.to_df())
    fig.show()

# Run the main function ONLY when this script is executed directly (not imported as a module).
if __name__ == "__main__":
    main()